/**
 * Read and write the authored insight catalog.
 *
 * `src/data/catalog.json` is regenerated by `scripts/build-data.ts` on every
 * `bun run dev`, so authored insights cannot be written there — they would be
 * erased on the next start. They go in `catalog/custom-insights.json`, beside
 * `insights.yaml` rather than inside it, so the hand-authored catalog stays
 * reviewable and this one can be regenerated or discarded without touching it.
 *
 * Deliberately NOT read through build-data: this endpoint serves the file at
 * runtime, so an insight authored in the UI appears immediately rather than on
 * the next vite start. Follows `analyse-endpoint.ts` — same plugin shape, same
 * `/api/*` middleware, same "the file on disk is the truth" posture.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import type { Connect, Plugin } from 'vite'

import type { AuthoredInsight, AuthoredInsightStore } from '../src/lib/customInsights'

// `process.cwd()` is the prototype directory; the catalog is its sibling.
const FILE = join(process.cwd(), '..', 'catalog', 'custom-insights.json')
/** Compile requests and their answers, alongside the analyses. */
const COMPILE_DIR = join(process.cwd(), 'analysis', 'insights')

const COMMENT =
  'Insights authored in the prototype’s Catalog tab. Machine-written: edit ' +
  'through the UI, not by hand. insights.yaml stays the hand-authored catalog; ' +
  'this file sits beside it so that one stays reviewable and this one can be ' +
  'regenerated or thrown away. Read at runtime by /api/insights, NOT by ' +
  'scripts/build-data.ts — so a new insight appears without restarting vite.'

const readBody = async (req: Connect.IncomingMessage) => {
  const chunks: Buffer[] = []
  for await (const c of req) chunks.push(c as Buffer)

  return Buffer.concat(chunks).toString()
}

/** A missing or malformed file yields an empty catalog rather than a 500: the
 *  authoring UI still has to open so the author can write the first one. */
const read = (): AuthoredInsight[] => {
  if (!existsSync(FILE)) return []
  try {
    const parsed = JSON.parse(readFileSync(FILE, 'utf8')) as AuthoredInsightStore

    return Array.isArray(parsed.insights) ? parsed.insights : []
  } catch {
    return []
  }
}

const write = (insights: AuthoredInsight[]) => {
  mkdirSync(dirname(FILE), { recursive: true })
  writeFileSync(FILE, `${JSON.stringify({ _comment: COMMENT, insights }, null, 2)}\n`)
}

/**
 * What makes an entry renderable. An insight with no statement or no id cannot
 * be shown as a row, so it is refused here rather than written and skipped
 * later — a file the UI silently ignores is worse than a rejected save.
 */
const problemWith = (value: unknown): string | null => {
  if (!value || typeof value !== 'object') return 'Not an insight object.'
  const insight = value as Partial<AuthoredInsight>
  if (!insight.id?.trim()) return 'The insight needs an id.'
  if (!insight.prompt?.trim()) return 'The insight needs the prompt it was written from.'
  if (!insight.compiled) return 'The insight has not been compiled yet.'
  if (!insight.compiled.relation) return 'The compiled insight needs a relation.'
  if (!Array.isArray(insight.compiled.sources)) return 'The compiled insight needs sources.'

  return null
}

/**
 * Hand a prompt to the Claude Code session to compile.
 *
 * Same posture as `analyse-endpoint.ts`: the request goes to disk, the session
 * reads it and writes the answer beside it, the UI polls. No API key and no
 * second model call — the session that knows the record shape is the one
 * mapping the prompt onto it, and can be asked to refine it in conversation.
 */
const queueCompile = (prompt: string) => {
  mkdirSync(COMPILE_DIR, { recursive: true })
  const id = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`
  writeFileSync(
    join(COMPILE_DIR, `request-${id}.json`),
    `${JSON.stringify({ id, prompt, requestedAt: new Date().toISOString() }, null, 2)}\n`
  )

  return id
}

/** The session's answer, or null while it is still being written. */
const readCompiled = (id: string) => {
  const path = join(COMPILE_DIR, `result-${id}.json`)
  if (!existsSync(path)) return null
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as unknown
  } catch {
    // Mid-write. The client keeps polling.
    return null
  }
}

export const insightsPlugin = (): Plugin => ({
  name: 'authored-insights',
  configureServer(server) {
    server.middlewares.use(async (req, res, next) => {
      const url = req.url ?? ''
      if (!url.startsWith('/api/insights')) return next()
      res.setHeader('Content-Type', 'application/json')

      if (url.startsWith('/api/insights/compile')) {
        if (req.method === 'POST') {
          const { prompt } = JSON.parse(await readBody(req)) as { prompt?: string }
          if (!prompt?.trim()) {
            res.statusCode = 400
            res.end(JSON.stringify({ error: 'Write what the insight should say.' }))

            return
          }
          const id = queueCompile(prompt)
          server.config.logger.info(
            `  \u22ef insight prompt queued \u2014 write analysis/insights/result-${id}.json`
          )
          res.end(JSON.stringify({ id }))

          return
        }

        if (req.method === 'GET') {
          const id = new URL(url, 'http://localhost').searchParams.get('id')
          const result = id ? readCompiled(id) : null
          if (!result) {
            res.statusCode = 404
            res.end(JSON.stringify({ pending: true }))

            return
          }
          res.end(JSON.stringify(result))

          return
        }
      }

      if (req.method === 'GET') {
        res.end(JSON.stringify({ insights: read() }))

        return
      }

      if (req.method === 'POST') {
        let incoming: unknown
        try {
          incoming = JSON.parse(await readBody(req))
        } catch {
          res.statusCode = 400
          res.end(JSON.stringify({ error: 'Body was not JSON.' }))

          return
        }

        const problem = problemWith(incoming)
        if (problem) {
          res.statusCode = 400
          res.end(JSON.stringify({ error: problem }))

          return
        }

        const insight = incoming as AuthoredInsight
        const existing = read()
        const at = existing.findIndex((i) => i.id === insight.id)
        const stamped = { ...insight, authored: true as const, updatedAt: new Date().toISOString() }
        const next =
          at === -1
            ? [...existing, stamped]
            : existing.map((i, index) => (index === at ? { ...stamped, createdAt: i.createdAt } : i))

        write(next)
        server.config.logger.info(
          `  ${at === -1 ? '+' : '~'} insight ${insight.id} (catalog/custom-insights.json)`
        )
        res.end(JSON.stringify({ insights: next }))

        return
      }

      if (req.method === 'DELETE') {
        const id = new URL(url, 'http://localhost').searchParams.get('id')
        if (!id) {
          res.statusCode = 400
          res.end(JSON.stringify({ error: 'No id given.' }))

          return
        }

        const next = read().filter((i) => i.id !== id)
        write(next)
        server.config.logger.info(`  - insight ${id} (catalog/custom-insights.json)`)
        res.end(JSON.stringify({ insights: next }))

        return
      }

      res.statusCode = 405
      res.end(JSON.stringify({ error: `${req.method} not supported here.` }))
    })
  }
})
